logging:
  level: INFO
  loggers:
    com.goals: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/postgres

logging:
  appenders:
  - type: file
    currentLogFilename: ./logs/temperature.log
    archivedLogFilenamePattern: ./logs/temperature-%d.log.gz
    archivedFileCount: 5
  - type: console
