logging:
  level: INFO
  loggers:
    com.temperature: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/postgres

logging:
  appenders:
  - type: file
    currentLogFilename: ./logs/goals.log
    archivedLogFilenamePattern: ./logs/goals-%d.log.gz
    archivedFileCount: 5
  - type: console
