logging:
  level: INFO
  loggers:
    com.logic: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

identHost: http://localhost:9004