logging:
  level: INFO
  loggers:
    com.logic: DEBUG

# http:
#   port: 9004
#   adminPort: 9005
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001